
function SHSM_GA_GROUPAUTOPTION_SQL() 
{

  str_QrySAO_OPTCODE="Select SAO_NAME , SAO_OPTCODE from SH_SM_AO_APPOPTION  WHERE SPT_PRGTYPECODE='~ddlSPT_PRGTYPECODE~' AND  SAA_APPCODE = '99'";
  str_QrySAN_SUBOPTCODE="Select SAN_NAME , SAN_SUBOPTCODE from SH_SM_AN_APPSUBOPTION  WHERE SAO_OPTCODE='~ddlSAO_OPTCODE~'";
  str_QrySAF_BUTTONCODE="Select SAF_NAME , SAF_BUTTONCODE from SH_SM_AF_APPBUTTON  WHERE SAN_SUBOPTCODE='~ddlSAN_SUBOPTCODE~'";
}

function SHSM_US_USER_SQL() 
{
  str_QrySUG_GROUPCODE="Select SUG_DESC , SUG_GROUPCODE from SH_SM_UG_USERGROUP  WHERE SAA_APPCODE='~ddlSAA_APPCODE~'";
}
function SHSM_UF_USERAUTGROUP_SQL()
{
	str_QrySUG_GROUPCODE="Select SUG_DESC , SUG_GROUPCODE from SH_SM_UG_USERGROUP  WHERE SAA_APPCODE='~ddlSAA_APPCODE~'";
}

function SHSM_UO_USERAUTOPTION_SQL() 
{
  str_QrySAO_OPTCODE="Select SAO_NAME , SAO_OPTCODE from SH_SM_AO_APPOPTION  WHERE SAA_APPCODE='~ddlSAA_APPCODE~'";
  str_QrySAN_SUBOPTCODE="Select SAN_NAME , SAN_SUBOPTCODE from SH_SM_AN_APPSUBOPTION  WHERE SAO_OPTCODE='~ddlSAO_OPTCODE~' ORDER BY SAN_NAME";
  str_QrySAF_BUTTONCODE="Select SAF_NAME , SAF_BUTTONCODE from SH_SM_AF_APPBUTTON  WHERE SAN_SUBOPTCODE='~ddlSAN_SUBOPTCODE~'";
}

function SHSM_UF_USERAUTOPTCOL_SQL(){
str_QrySAO_OPTCODE="Select SAO_NAME , SAO_OPTCODE from SH_SM_AO_APPOPTION  WHERE SAA_APPCODE='~ddlSAA_APPCODE~'";
str_QrySAN_SUBOPTCODE="Select SAN_NAME , SAN_SUBOPTCODE from SH_SM_AN_APPSUBOPTION  WHERE SAO_OPTCODE='~ddlSAO_OPTCODE~'";
str_QrySAS_COLUMNCODE="Select SAS_COLUMNNAME , SAS_COLUMNCODE from SH_SM_AS_APPSUBOPTIONCOL  WHERE SAN_SUBOPTCODE='~ddlSAN_SUBOPTCODE~'";
}


function SHSM_AM_APPMENU_SQL()
{
	str_QrySAO_OPTCODE="Select SAO_NAME,SAO_OPTCODE  from SH_SM_AO_APPOPTION  WHERE SPT_PRGTYPECODE='~ddlSPT_PRGTYPECODE~' AND  SAA_APPCODE = '99'";
	str_QrySAN_SUBOPTCODE="Select SAN_NAME,SAN_SUBOPTCODE from SH_SM_AN_APPSUBOPTION  WHERE SAO_OPTCODE='~ddlSAO_OPTCODE~'";
}