//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHAB.Presentation {
    
    
    public partial class shgn_bt_se_button_ILUS_ET_UC_USERCHANNEL {
        
        /// <summary>
        /// cmd_Save control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SHMA.CodeVision.Presentation.WebControls.CustomButton cmd_Save;
        
        /// <summary>
        /// cmd_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SHMA.CodeVision.Presentation.WebControls.CustomButton cmd_Delete;
        
        /// <summary>
        /// cmd_Menu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SHMA.CodeVision.Presentation.WebControls.CustomButton cmd_Menu;
    }
}
